apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# NOTE(hsiny): namespace here is going to overwirte all resources' namespace below
generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true
resources:
- ./namespace.yaml
- ./istio-gateway.yaml
- ./service-account.yaml
helmCharts:
- name: istiod # chart name
  includeCRDs: True # turn on when first time installation, leverage the one on kubeflow's installation
  namespace: istio-system
  releaseName: istio-istiod
  version: 1.16.0
  repo: https://istio-release.storage.googleapis.com/charts
#- name: gateway # chart name
#  includeCRDs: True # turn on when first time installation, leverage the one on kubeflow's installation
#  namespace: istio-system
#  releaseName: istio-gateway
#  version: 1.16.0
#  repo: https://istio-release.storage.googleapis.com/charts
- name: base # chart name
  includeCRDs: True # turn on when first time installation, leverage the one on kubeflow's installation
  namespace: istio-system
  releaseName: istio-base
  version: 1.16.0
  repo: https://istio-release.storage.googleapis.com/charts
