apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: istio-gateway
    app.footprint-ai.com/mainapp: tintin
    app.footprint-ai.com/variant: dev01
    app.footprint-ai.com/version: dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: istio-gateway
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: gateway-1.16.0
    istio: gateway
  name: istio-ingressgateway-service-account
  namespace: istio-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.footprint-ai.com/mainapp: tintin
    app.footprint-ai.com/variant: dev01
    app.footprint-ai.com/version: dev
  name: istio-gateway
  namespace: istio-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.footprint-ai.com/mainapp: tintin
    app.footprint-ai.com/variant: dev01
    app.footprint-ai.com/version: dev
  name: istio-gateway-role-binding
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istio-gateway
subjects:
- kind: ServiceAccount
  name: istio-ingressgateway-service-account

