apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
- ./namespace.yaml
- ./cluster-issuer.yaml
helmCharts:
- name: cert-manager # chart name
  includeCRDs: True
  ValuesFile: values.yaml
  namespace: cert-manager
  releaseName: jetstack-cert-manager
  version: v1.12.2
  repo: https://charts.jetstack.io
