apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bench-ingress-cert
  namespace: istio-system
spec:
  secretName: bench-ingress-cert
  issuerRef:
    name: letsencrypt-production-istio
    kind: ClusterIssuer
  dnsNames:
  - bench.dev01.footprint-ai.com
