apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-inference.yaml
- deployment-userresource.yaml
- gateway.yaml
- service-inference.yaml
- service-userresource.yaml
- virtualservice.yaml
- namespace.yaml
- certificate.yaml
- service-monitor.yaml
