apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor
  namespace: bench
  labels:
    app: kafeido-monitoring
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      monitoring: enabled
  endpoints:
  - port: http-metrics
